import {APP_LANGUAGES, getAppLanguage, setAppLanguage} from './languagePreferences';

export const CALENDAR_LANGUAGES = {
  RU: APP_LANGUAGES.RU,
  UK: APP_LANGUAGES.UK,
};

export const getCalendarLanguage = getAppLanguage;

export const setCalendarLanguage = setAppLanguage;

const CALENDAR_COPY = {
  ru: {
    language: 'ru',
    calendarTitle: 'Церковный календарь',
    allCalendar: 'Весь календарь',
    today: 'Сегодня',
    selectedDay: 'Выбранный день',
    saintMemory: 'Память дня',
    greatFeast: 'Великий праздник',
    noFastData: 'Пост: нет данных',
    noFast: 'Поста нет',
    alsoToday: 'ТАКЖЕ В ЭТОТ ДЕНЬ',
    noOtherMemories: 'Другие памяти не указаны',
    life: 'Житие',
    troparion: 'Тропарь',
    kontakion: 'Кондак',
    readings: 'ЧТЕНИЯ ДНЯ',
    gospel: 'ЕВАНГЕЛИЕ ДНЯ',
    apostle: 'АПОСТОЛ ДНЯ',
    openBible: 'Открыть в Библии',
    unrecognized: 'Ссылка пока не распознана',
    readText: 'Читать текст',
    hideText: 'Скрыть текст',
    noReadings: 'Чтения для этого дня пока не указаны',
    noData: 'Нет данных для выбранного дня',
    loadingMemory: 'Загружаем память дня…',
    loadingDay: 'Загрузка дня…',
    loadCalendarError: 'Не удалось загрузить календарь',
    loadDayError: 'Не удалось загрузить день',
    onScreen: 'На экран',
    widgetAlready: 'Виджет уже добавлен',
    widgetName: 'Церковный календарь',
    chapter: 'Глава',
    hideExtraReadings: 'Скрыть дополнительные чтения',
    moreReadings: 'Ещё чтений: {count}',
    feastMemory: 'ПАМЯТЬ СВЯТОГО / ПРАЗДНИК',
    voice: 'Глас',
  },
  uk: {
    language: 'uk',
    calendarTitle: 'Церковний календар',
    allCalendar: 'Весь календар',
    today: 'Сьогодні',
    selectedDay: 'Обраний день',
    saintMemory: 'Пам’ять дня',
    greatFeast: 'Велике свято',
    noFastData: 'Піст: немає даних',
    noFast: 'Посту немає',
    alsoToday: 'ТАКОЖ ЦЬОГО ДНЯ',
    noOtherMemories: 'Інші пам’яті не вказані',
    life: 'Житіє',
    troparion: 'Тропар',
    kontakion: 'Кондак',
    readings: 'ЧИТАННЯ ДНЯ',
    gospel: 'ЄВАНГЕЛІЄ ДНЯ',
    apostle: 'АПОСТОЛ ДНЯ',
    openBible: 'Відкрити в Біблії',
    unrecognized: 'Посилання поки не розпізнано',
    readText: 'Читати текст',
    hideText: 'Сховати текст',
    noReadings: 'Читання для цього дня поки не вказані',
    noData: 'Немає даних для обраного дня',
    loadingMemory: 'Завантажуємо пам’ять дня…',
    loadingDay: 'Завантаження дня…',
    loadCalendarError: 'Не вдалося завантажити календар',
    loadDayError: 'Не вдалося завантажити день',
    onScreen: 'На екран',
    widgetAlready: 'Віджет уже додано',
    widgetName: 'Церковний календар',
    chapter: 'Розділ',
    hideExtraReadings: 'Згорнути додаткові читання',
    moreReadings: 'Ще читань: {count}',
    feastMemory: 'ПАМ’ЯТЬ СВЯТОГО / СВЯТО',
    voice: 'Глас',
  },
};

export const calendarText = (language) => CALENDAR_COPY[language] || CALENDAR_COPY.ru;

export const CALENDAR_MONTHS = {
  ru: {
    nominative: [
      'Январь',
      'Февраль',
      'Март',
      'Апрель',
      'Май',
      'Июнь',
      'Июль',
      'Август',
      'Сентябрь',
      'Октябрь',
      'Ноябрь',
      'Декабрь',
    ],
    genitive: [
      'января',
      'февраля',
      'марта',
      'апреля',
      'мая',
      'июня',
      'июля',
      'августа',
      'сентября',
      'октября',
      'ноября',
      'декабря',
    ],
    weekdays: ['воскресенье', 'понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота'],
    miniWeekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
  },
  uk: {
    nominative: [
      'Січень',
      'Лютий',
      'Березень',
      'Квітень',
      'Травень',
      'Червень',
      'Липень',
      'Серпень',
      'Вересень',
      'Жовтень',
      'Листопад',
      'Грудень',
    ],
    genitive: [
      'січня',
      'лютого',
      'березня',
      'квітня',
      'травня',
      'червня',
      'липня',
      'серпня',
      'вересня',
      'жовтня',
      'листопада',
      'грудня',
    ],
    weekdays: ['неділя', 'понеділок', 'вівторок', 'середа', 'четвер', 'п’ятниця', 'субота'],
    miniWeekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд'],
  },
};
