# Generated by Django 6.1 on 2026-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('psalter', 'Псалтырь'), ('gospel', 'Евангелие'), ('akathist', 'Акакфист'), ('prayer', 'Молитва'), ('bible', 'Библия')], max_length=20)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
