# Generated by Django 6.1 on 2026-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rule_text_translation_ruleitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ruleitem',
            constraint=models.UniqueConstraint(fields=('rule', 'order'), name='unique_order_per_rule'),
        ),
    ]
