# Generated by Django 6.1 on 2026-09-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ruleitem_unique_order_per_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytext',
            options={'ordering': ['order'], 'verbose_name': 'Текст в категории', 'verbose_name_plural': 'Тексты в категориях'},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['order'], 'verbose_name': 'Текст в сборнике', 'verbose_name_plural': 'Тексты в сборниках'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Молитвенное правило', 'verbose_name_plural': 'Молитвенные правила'},
        ),
        migrations.AlterModelOptions(
            name='ruleitem',
            options={'ordering': ['order'], 'verbose_name': 'Текст в правиле', 'verbose_name_plural': 'Тексты в правилах'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Молитва / текст', 'verbose_name_plural': 'Молитвы и тексты'},
        ),
        migrations.AlterModelOptions(
            name='usercollection',
            options={'verbose_name': 'Пользовательский сборник', 'verbose_name_plural': 'Пользовательские сборники'},
        ),
    ]
