# Generated by Django 6.1 on 2026-09-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_prayerruleitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kathisma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер кафизмы')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кафизма',
                'verbose_name_plural': 'Кафизмы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Psalter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Url-индетификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'Псалтирь',
                'verbose_name_plural': 'Псалтири',
            },
        ),
        migrations.CreateModel(
            name='Psalm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер псалма')),
                ('title_church_slavonic', models.CharField(blank=True, max_length=500, verbose_name='Заголовок на церковнославянском')),
                ('title_russian', models.CharField(blank=True, max_length=500, verbose_name='Заголовок на русском')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание псалма')),
                ('kathisma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psalms', to='api.kathisma', verbose_name='Кафизма')),
            ],
            options={
                'verbose_name': 'Псалом',
                'verbose_name_plural': 'Псалмы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PsalmVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер стиха')),
                ('church_slavonic', models.TextField(verbose_name='Церковнославянский текст')),
                ('russian', models.TextField(blank=True, verbose_name='Русский текст')),
                ('psalm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='api.psalm', verbose_name='Псалом')),
            ],
            options={
                'verbose_name': 'Стих псалма',
                'verbose_name_plural': 'Стихи псалмов',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='KathismaGlory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер Славы')),
                ('kathisma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glories', to='api.kathisma', verbose_name='Кафизма')),
                ('after_psalm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glories_after', to='api.psalm', verbose_name='После псалма')),
                ('after_verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glories_after', to='api.psalmverse', verbose_name='После стиха')),
            ],
            options={
                'verbose_name': 'Слава кафизмы',
                'verbose_name_plural': 'Славы кафизм',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='kathisma',
            name='psalter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kathisma', to='api.psalter', verbose_name='Псалтирь'),
        ),
        migrations.AddConstraint(
            model_name='psalmverse',
            constraint=models.UniqueConstraint(fields=('psalm', 'number'), name='unique_verbose_per_psalm'),
        ),
        migrations.AddConstraint(
            model_name='kathismaglory',
            constraint=models.UniqueConstraint(fields=('kathisma', 'number'), name='unique_glory_per_kathisma'),
        ),
        migrations.AddConstraint(
            model_name='kathismaglory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('after_psalm__isnull', False), ('after_verse__isnull', True)), models.Q(('after_psalm__isnull', True), ('after_verse__isnull', False)), _connector='OR'), name='kathisma_glory_position_required'),
        ),
        migrations.AddConstraint(
            model_name='kathisma',
            constraint=models.UniqueConstraint(fields=('psalter', 'number'), name='unique_kathisma_per_psalter'),
        ),
    ]
