# Generated by Django 6.1 on 2026-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_psalter_prayers_after_psalter_prayers_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='kathisma',
            name='prayers_after',
            field=models.TextField(blank=True, verbose_name='Молитвы после кафизмы'),
        ),
    ]
