# Generated by Django 6.1 on 2026-09-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_kathisma_prayers_after'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50, verbose_name='Тип источника')),
                ('source_id', models.PositiveIntegerField(verbose_name='ID источника')),
                ('anchor_type', models.CharField(blank=True, max_length=50, verbose_name='Тип позиции')),
                ('anchor_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID позиции')),
                ('offset', models.PositiveIntegerField(default=0, verbose_name='Смещение внутри єлемента')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'source_type', 'source_id'), name='unique_reading_progress_per_source')],
            },
        ),
    ]
