# Generated by Django 6.1 on 2026-09-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_akathist_akathistsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='akathist',
            name='kontakion_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akathists_as_kontakion_before', to='api.text', verbose_name='Кондак перед акафистом'),
        ),
        migrations.AddField(
            model_name='akathist',
            name='troparion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akathists_as_troparion', to='api.text', verbose_name='Тропарь перед акафистом'),
        ),
        migrations.CreateModel(
            name='AkathistReadingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True, verbose_name='Ключ')),
                ('ending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akathist_ending_rules', to='api.text', verbose_name='Общее окончание акафиста')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akathist_opening_rules', to='api.text', verbose_name='Общее начало акафиста')),
            ],
            options={
                'verbose_name': 'Общий чин чтения акафиста',
                'verbose_name_plural': 'Общий чин чтения акафиста',
            },
        ),
    ]
