from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'api',
            '0020_alter_saveditem_add_fragment',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Canon',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255,
                        verbose_name='Название',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        unique=True,
                        verbose_name='URL-идентификатор',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        verbose_name='Описание',
                    ),
                ),
                (
                    'tone',
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name='Глас',
                    ),
                ),
                (
                    'is_visible',
                    models.BooleanField(
                        default=True,
                        verbose_name='Отображать',
                    ),
                ),
            ],
            options={
                'verbose_name':
                    'Канон',
                'verbose_name_plural':
                    'Каноны',
            },
        ),

        migrations.CreateModel(
            name='CanonSection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'section_type',
                    models.CharField(
                        choices=[
                            (
                                'irmos',
                                'Ирмос',
                            ),
                            (
                                'refrain',
                                'Припев',
                            ),
                            (
                                'troparion',
                                'Тропарь',
                            ),
                            (
                                'theotokion',
                                'Богородичен',
                            ),
                            (
                                'glory',
                                'Слава',
                            ),
                            (
                                'now',
                                'И ныне',
                            ),
                            (
                                'sedalen',
                                'Седален',
                            ),
                            (
                                'kontakion',
                                'Кондак',
                            ),
                            (
                                'ikos',
                                'Икос',
                            ),
                            (
                                'svetilen',
                                'Светилен',
                            ),
                            (
                                'prayer',
                                'Молитва',
                            ),
                            (
                                'other',
                                'Прочее',
                            ),
                        ],
                        default='other',
                        max_length=20,
                        verbose_name='Тип элемента',
                    ),
                ),
                (
                    'variant',
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name='Вариант',
                    ),
                ),
                (
                    'ode_number',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name='Номер песни',
                    ),
                ),
                (
                    'heading',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Заголовок / метка',
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name='Порядок',
                    ),
                ),
                (
                    'canon',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sections',
                        to='api.canon',
                        verbose_name='Канон',
                    ),
                ),
                (
                    'text',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='canon_sections',
                        to='api.text',
                        verbose_name='Текст',
                    ),
                ),
            ],
            options={
                'verbose_name':
                    'Элемент канона',
                'verbose_name_plural':
                    'Элементы канона',
                'ordering': [
                    'variant',
                    'order',
                ],
            },
        ),

        migrations.AddConstraint(
            model_name='canonsection',
            constraint=models.UniqueConstraint(
                fields=(
                    'canon',
                    'variant',
                    'order',
                ),
                name='unique_order_per_canon_variant',
            ),
        ),

        migrations.AlterField(
            model_name='saveditem',
            name='save_type',
            field=models.CharField(
                choices=[
                    (
                        'word',
                        'Слово',
                    ),
                    (
                        'sentence',
                        'Предложение',
                    ),
                    (
                        'paragraph',
                        'Абзац',
                    ),
                    (
                        'fragment',
                        'Фрагмент',
                    ),
                    (
                        'verse',
                        'Стих',
                    ),
                    (
                        'section',
                        'Раздел',
                    ),
                    (
                        'prayer',
                        'Молитва',
                    ),
                    (
                        'psalm',
                        'Псалом',
                    ),
                    (
                        'kathisma',
                        'Кафизма',
                    ),
                    (
                        'chapter',
                        'Глава',
                    ),
                    (
                        'akathist',
                        'Акафист',
                    ),
                    (
                        'canon',
                        'Канон',
                    ),
                    (
                        'text',
                        'Текст',
                    ),
                ],
                max_length=30,
                verbose_name='Тип сохранения',
            ),
        ),
    ]
