# Generated by Django 6.1 on 2026-09-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_psalter_prayers_after_russian_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kathisma",
            name="prayers_after_russian",
            field=models.TextField(blank=True, verbose_name="Молитвы после кафизмы — русский"),
        ),
    ]
