# Generated by Django 6.1 on 2026-09-29 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_kathisma_prayers_after_russian"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "google_sub",
                    models.CharField(max_length=255, unique=True, verbose_name="Google user ID"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Google email")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Имя")),
                ("picture_url", models.URLField(blank=True, verbose_name="Фото профиля")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google-аккаунт",
                "verbose_name_plural": "Google-аккаунты",
            },
        ),
    ]
