# Generated by Django 6.1 on 2026-09-29 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_backfill_saveditem_sync_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID синхронизации'),
        ),
    ]
