# Generated by Django 6.1 on 2026-09-29 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_saveditem_sync_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingprogress",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="readingprogress",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="Дополнительные данные"),
        ),
        migrations.AddField(
            model_name="readingprogress",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Прогресс в процентах"),
        ),
        migrations.AlterField(
            model_name="readingprogress",
            name="offset",
            field=models.PositiveIntegerField(default=0, verbose_name="Смещение внутри элемента"),
        ),
        migrations.AlterField(
            model_name="readingprogress",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Обновлено"),
        ),
    ]
